Rn mkhh #30
KonradCencelewicz/megak-head-hunter-be pull request #11
Opened 2023-04-23 22:10 UTC by darkRaf

W pliku refresh.ts w 21 linii wstawiłem any ;( 
próbowałem na różne sposoby zadeklarować typ - linia 8, ale TS ciągle się czepiał.

2023-04-25 20:32 UTC, Alendart commented on routers/login.router.ts
> +    if (!user) throw new Error('Podnay amail nie istnieje.');
Literówki w errorze

2023-04-25 20:44 UTC, Alendart commented on routers/logout.routers.ts
> +  const refreshToken = req.cookies.refreshToken as string;
Nie lepiej użyć metody post? Tak sugeruje internet w tym temacie. metoda delete chyba powinna być używana tylko do usuwania czegoś po stronie serwera, a my tylko czyścimy ciastka

2023-04-25 20:48 UTC, Alendart commented on routers/register.router.ts
> +    const hashPass = bcrypt.hashSync(password, 14);
Nie uważasz że hashowanie hasła, zwłaszcza przy 14 cyklach nie powinno być robione asynchronicznie?

2023-04-25 20:50 UTC, Alendart requested changes
Dodałem komentarze w kodzie

2023-04-26 16:56 UTC, Alendart approved these changes
All seems ok

2023-04-26 17:04 UTC, JarekKrolik approved these changes
znalazłem literówkę w komunikacie błędnego emaila, poza tym błędów nie widzę

2023-04-26 17:04 UTC, JarekKrolik commented on routers/register.router.ts
> +    if (!user) throw new Error('Podany adres amail nie istnieje. Proszę skontakotwać się z administratorem serwisu.');
literówka amail - email

2023-04-26 19:07 UTC, merged